name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          auto-activate-base: false
      - run: |
          conda install cudatoolkit
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest poetry
          pip install -U spacy
          python -m spacy download en_core_web_sm
      - uses: chartboost/ruff-action@v1
      - name: Test with pytest
        run: |
          poetry build
          pip install dist/*.whl
          pytest
