# https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/configuration-guide.md
models:
  - type: main
    engine: amazon_bedrock
    model: anthropic
    parameters:
      temperature: 0
      streaming: True

rails:
  dialog:
    single_call:
      enabled: False

      # If a single call fails, whether to fall back to multiple LLM calls.
      fallback_to_multiple_calls: True

    user_messages:
      # Whether to use only the embeddings when interpreting the user's message
      embeddings_only: False
