version: "3.7"

services:
  code_search_demo:
    build: .
    container_name: code_search_demo
    env_file:
      - ../../.env
    ports:
      - 8000:8000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
